@2.TypedResults_HostAddress = https://localhost:7099

POST {{2.TypedResults_HostAddress}}/events
Content-Type: application/json

{
  "title": "JS hackathon",
  "description": "Networking and talks",
  "startTime": "2025-09-10T09:00:00",
  "endTime": "2025-09-10T17:00:00",
  "capacity": 150
}
###

GET {{2.TypedResults_HostAddress}}/events

###

GET {{2.TypedResults_HostAddress}}/events/1

###

PUT {{2.TypedResults_HostAddress}}/events/1
Content-Type: application/json

{
  "id": 1,
  "title": "Annual Meetup - Updated",
  "description": "Networking, and workshops",
  "startTime": "2025-09-10T09:00:00",
  "endTime": "2025-09-10T18:00:00",
  "capacity": 245
} 


###

DELETE {{2.TypedResults_HostAddress}}/events/1

###
